# Generated by Django 2.2.7 on 2020-06-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_temp_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_alert',
            name='candle',
        ),
        migrations.RemoveField(
            model_name='temp_alert',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='code',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='configuration_format',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Temp_Alert',
        ),
    ]
