# Generated by Django 2.2.7 on 2020-06-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200607_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='extra_output_lines',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_line_format',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='inputs_type',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='line_default_inputs',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Indicator_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_values', models.TextField(default=None, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Indicator')),
            ],
        ),
    ]
