# Generated by Django 2.2.7 on 2020-06-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_indicator_log_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='applied_on',
            field=models.ManyToManyField(to='app.Instrument'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='created_by_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerts',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
    ]
