# Generated by Django 2.2.7 on 2020-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200616_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
