# Generated by Django 2.2.7 on 2020-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alerts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='enabled',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
