# Generated by Django 2.2.7 on 2020-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alerts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='indicator_log',
            field=models.ManyToManyField(to='app.Indicator_log'),
        ),
    ]
