# Generated by Django 2.2.7 on 2020-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alerts_indicator_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator_log',
            name='display_line',
            field=models.TextField(default=None, null=True),
        ),
    ]
