# Generated by Django 2.2.7 on 2020-06-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_indicator_log_display_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alerts')),
            ],
        ),
    ]
